# Generated by Django 4.2.6 on 2025-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='account_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together={('account_phone', 'chat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('dialog', 'text', 'date')},
        ),
    ]
