# Generated by Django 4.2.6 on 2025-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0002_alter_dialog_account_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_outgoing',
            field=models.BooleanField(default=False),
        ),
    ]
