# Generated by Django 4.2.6 on 2025-09-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0003_message_delivered_message_is_outgoing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
    ]
