# Generated by Django 4.2.6 on 2025-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0005_remove_message_is_outgoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
