# Generated by Django 4.2.6 on 2025-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0006_message_media_file_message_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
