# Generated by Django 4.2.6 on 2025-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0007_alter_message_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
