# Generated by Django 4.2.6 on 2025-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0012_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
