# Generated by Django 4.2.6 on 2025-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0013_message_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
